@DocX.DocumentAI.Server_HostAddress = http://localhost:5243

POST {{DocX.DocumentAI.Server_HostAddress}}/api/document-ai/process
Content-Type: application/json

{
	"messages": [
		{
			"role": "user",
			"content": "Hello"
		}
	]
}

###
